name: CMake

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install libs
      run: sudo apt-get install libwxgtk-webview3.0-gtk3-0v5 libwxgtk-media3.0-gtk3-0v5 libgtk-3-dev -y
      
    - name: download and extract wxWidgets
      run: wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.5/wxWidgets-3.1.5.tar.bz2 && tar -xvf wxWidgets-3.1.5.tar.bz2 && cd wxWidgets-3.1.5/
      
    - name: build and install wxWidgets
      run: cd wxWidgets-3.1.5/ && mkdir gtk-build/ && cd gtk-build/ && cmake -S .. -B . && sudo make install

    - name: Configure and Build CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build 

    - name: build WeightChecker
      run: cd ${{github.workspace}}/build && make -j2
      
    - uses: actions/upload-artifact@v2
      with:
        name: do-not-download-unless-dumb
        path: |
          ${{github.workspace}}/build/WeightChecker
      
